/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp;

import com.astroapp.controllers.*;
import com.astroapp.http.client.HttpClient;

public class AstroAppRESTAPIsClient {
    /**
     * Singleton access to PredictiveCalculations controller
     * @return	Returns the PredictiveCalculationsController instance 
     */
    public PredictiveCalculationsController getPredictiveCalculations() {
        return PredictiveCalculationsController.getInstance();
    }

    /**
     * Singleton access to LocationsAndTimeZones controller
     * @return	Returns the LocationsAndTimeZonesController instance 
     */
    public LocationsAndTimeZonesController getLocationsAndTimeZones() {
        return LocationsAndTimeZonesController.getInstance();
    }

    /**
     * Singleton access to ChartsAndDetails controller
     * @return	Returns the ChartsAndDetailsController instance 
     */
    public ChartsAndDetailsController getChartsAndDetails() {
        return ChartsAndDetailsController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public AstroAppRESTAPIsClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public AstroAppRESTAPIsClient(String oAuthAccessToken) {
        this();
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}