/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class CalcRequestPropsBuilder {
    //the instance to build
    private CalcRequestProps calcRequestProps;

    /**
     * Default constructor to initialize the instance
     */
    public CalcRequestPropsBuilder() {
        calcRequestProps = new CalcRequestProps();
    }

    /**
     * Y: request image generation, N: don't request (faster, default option).
     */
    public CalcRequestPropsBuilder needImage(String needImage) {
        calcRequestProps.setNeedImage(needImage);
        return this;
    }

    /**
     * Y: Include aspects listing, N: don't include
     */
    public CalcRequestPropsBuilder needAspects(String needAspects) {
        calcRequestProps.setNeedAspects(needAspects);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CalcRequestProps build() {
        return calcRequestProps;
    }
}