/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CalcRequestProps 
        implements java.io.Serializable {
    private static final long serialVersionUID = -9045191540704222769L;
    private String needImage = "N";
    private String needAspects = "N";
    /** GETTER
     * Y: request image generation, N: don't request (faster, default option).
     */
    @JsonGetter("needImage")
    public String getNeedImage ( ) { 
        return this.needImage;
    }
    
    /** SETTER
     * Y: request image generation, N: don't request (faster, default option).
     */
    @JsonSetter("needImage")
    public void setNeedImage (String value) { 
        this.needImage = value;
    }
 
    /** GETTER
     * Y: Include aspects listing, N: don't include
     */
    @JsonGetter("needAspects")
    public String getNeedAspects ( ) { 
        return this.needAspects;
    }
    
    /** SETTER
     * Y: Include aspects listing, N: don't include
     */
    @JsonSetter("needAspects")
    public void setNeedAspects (String value) { 
        this.needAspects = value;
    }
 
}
