/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ChartDataResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3389154366680756050L;
    private Boolean calcResultsAvailable;
    private ChartData chartData;
    private List<Integer> houseCusps;
    private List<Object> objects;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("calcResultsAvailable")
    public Boolean getCalcResultsAvailable ( ) { 
        return this.calcResultsAvailable;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("calcResultsAvailable")
    public void setCalcResultsAvailable (Boolean value) { 
        this.calcResultsAvailable = value;
    }
 
    /** GETTER
     * Chart information: date, time, location, time zone, calculation parameters, such as House system, Zodiac type, Coordinates system and so on.
     */
    @JsonGetter("chartData")
    public ChartData getChartData ( ) { 
        return this.chartData;
    }
    
    /** SETTER
     * Chart information: date, time, location, time zone, calculation parameters, such as House system, Zodiac type, Coordinates system and so on.
     */
    @JsonSetter("chartData")
    public void setChartData (ChartData value) { 
        this.chartData = value;
    }
 
    /** GETTER
     * Positions of the house cusps.
     */
    @JsonGetter("houseCusps")
    public List<Integer> getHouseCusps ( ) { 
        return this.houseCusps;
    }
    
    /** SETTER
     * Positions of the house cusps.
     */
    @JsonSetter("houseCusps")
    public void setHouseCusps (List<Integer> value) { 
        this.houseCusps = value;
    }
 
    /** GETTER
     * Array of objects details - positions of the planets, asteroids, etc.
     */
    @JsonGetter("objects")
    public List<Object> getObjects ( ) { 
        return this.objects;
    }
    
    /** SETTER
     * Array of objects details - positions of the planets, asteroids, etc.
     */
    @JsonSetter("objects")
    public void setObjects (List<Object> value) { 
        this.objects = value;
    }
 
}
