/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ChartDataRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5397913102407719320L;
    private Chart chart;
    private CalcRequestProps calcRequestProps;
    private Params params;
    /** GETTER
     * Chart data (date/time, location, etc)
     */
    @JsonGetter("chart")
    public Chart getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * Chart data (date/time, location, etc)
     */
    @JsonSetter("chart")
    public void setChart (Chart value) { 
        this.chart = value;
    }
 
    /** GETTER
     * Properties define what to include in the response.
     */
    @JsonGetter("calcRequestProps")
    public CalcRequestProps getCalcRequestProps ( ) { 
        return this.calcRequestProps;
    }
    
    /** SETTER
     * Properties define what to include in the response.
     */
    @JsonSetter("calcRequestProps")
    public void setCalcRequestProps (CalcRequestProps value) { 
        this.calcRequestProps = value;
    }
 
    /** GETTER
     * Calculation parameters.
     */
    @JsonGetter("params")
    public Params getParams ( ) { 
        return this.params;
    }
    
    /** SETTER
     * Calculation parameters.
     */
    @JsonSetter("params")
    public void setParams (Params value) { 
        this.params = value;
    }
 
}
