/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ChartDataRequestBuilder {
    //the instance to build
    private ChartDataRequest chartDataRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ChartDataRequestBuilder() {
        chartDataRequest = new ChartDataRequest();
    }

    /**
     * Chart data (date/time, location, etc)
     */
    public ChartDataRequestBuilder chart(Chart chart) {
        chartDataRequest.setChart(chart);
        return this;
    }

    /**
     * Properties define what to include in the response.
     */
    public ChartDataRequestBuilder calcRequestProps(CalcRequestProps calcRequestProps) {
        chartDataRequest.setCalcRequestProps(calcRequestProps);
        return this;
    }

    /**
     * Calculation parameters.
     */
    public ChartDataRequestBuilder params(Params params) {
        chartDataRequest.setParams(params);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ChartDataRequest build() {
        return chartDataRequest;
    }
}