/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Chart 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4903119157673822475L;
    private ChartData chartData;
    private Boolean calcResultsAvailable;
    private List<Double> houseCusps;
    private List<Object> objects;
    private List<Double> spectialPoints;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chartData")
    public ChartData getChartData ( ) { 
        return this.chartData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chartData")
    public void setChartData (ChartData value) { 
        this.chartData = value;
    }
 
    /** GETTER
     * Optional parameter indicating that the chart has been calculated already.
     */
    @JsonGetter("calcResultsAvailable")
    public Boolean getCalcResultsAvailable ( ) { 
        return this.calcResultsAvailable;
    }
    
    /** SETTER
     * Optional parameter indicating that the chart has been calculated already.
     */
    @JsonSetter("calcResultsAvailable")
    public void setCalcResultsAvailable (Boolean value) { 
        this.calcResultsAvailable = value;
    }
 
    /** GETTER
     * Array of house cusps positions.
     */
    @JsonGetter("houseCusps")
    public List<Double> getHouseCusps ( ) { 
        return this.houseCusps;
    }
    
    /** SETTER
     * Array of house cusps positions.
     */
    @JsonSetter("houseCusps")
    public void setHouseCusps (List<Double> value) { 
        this.houseCusps = value;
    }
 
    /** GETTER
     * Array of objects details - positions of the planets, asteroids, etc.
     */
    @JsonGetter("objects")
    public List<Object> getObjects ( ) { 
        return this.objects;
    }
    
    /** SETTER
     * Array of objects details - positions of the planets, asteroids, etc.
     */
    @JsonSetter("objects")
    public void setObjects (List<Object> value) { 
        this.objects = value;
    }
 
    /** GETTER
     * Special points array may optionally be included in requests and responses.
     */
    @JsonGetter("spectialPoints")
    public List<Double> getSpectialPoints ( ) { 
        return this.spectialPoints;
    }
    
    /** SETTER
     * Special points array may optionally be included in requests and responses.
     */
    @JsonSetter("spectialPoints")
    public void setSpectialPoints (List<Double> value) { 
        this.spectialPoints = value;
    }
 
}
