/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ChartDataResponseBuilder {
    //the instance to build
    private ChartDataResponse chartDataResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ChartDataResponseBuilder() {
        chartDataResponse = new ChartDataResponse();
    }

    public ChartDataResponseBuilder calcResultsAvailable(Boolean calcResultsAvailable) {
        chartDataResponse.setCalcResultsAvailable(calcResultsAvailable);
        return this;
    }

    /**
     * Chart information: date, time, location, time zone, calculation parameters, such as House system, Zodiac type, Coordinates system and so on.
     */
    public ChartDataResponseBuilder chartData(ChartData chartData) {
        chartDataResponse.setChartData(chartData);
        return this;
    }

    /**
     * Positions of the house cusps.
     */
    public ChartDataResponseBuilder houseCusps(List<Integer> houseCusps) {
        chartDataResponse.setHouseCusps(houseCusps);
        return this;
    }

    /**
     * Array of objects details - positions of the planets, asteroids, etc.
     */
    public ChartDataResponseBuilder objects(List<Object> objects) {
        chartDataResponse.setObjects(objects);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ChartDataResponse build() {
        return chartDataResponse;
    }
}