/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ChartBuilder {
    //the instance to build
    private Chart chart;

    /**
     * Default constructor to initialize the instance
     */
    public ChartBuilder() {
        chart = new Chart();
    }

    public ChartBuilder chartData(ChartData chartData) {
        chart.setChartData(chartData);
        return this;
    }

    /**
     * Optional parameter indicating that the chart has been calculated already.
     */
    public ChartBuilder calcResultsAvailable(Boolean calcResultsAvailable) {
        chart.setCalcResultsAvailable(calcResultsAvailable);
        return this;
    }

    /**
     * Array of house cusps positions.
     */
    public ChartBuilder houseCusps(List<Double> houseCusps) {
        chart.setHouseCusps(houseCusps);
        return this;
    }

    /**
     * Array of objects details - positions of the planets, asteroids, etc.
     */
    public ChartBuilder objects(List<Object> objects) {
        chart.setObjects(objects);
        return this;
    }

    /**
     * Special points array may optionally be included in requests and responses.
     */
    public ChartBuilder spectialPoints(List<Double> spectialPoints) {
        chart.setSpectialPoints(spectialPoints);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Chart build() {
        return chart;
    }
}