/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ChartData 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2250993716265111942L;
    private String chartName;
    private String chartDate;
    private String lng;
    private String lat;
    private int elev;
    private String tz;
    private int zodiacID = 100;
    private int houseSystemID = 1;
    private String coordSys = "G";
    private int version = 1;
    private String imgPath = "\"\"";
    private Double jd = 0d;
    /** GETTER
     * Chart name
     */
    @JsonGetter("chartName")
    public String getChartName ( ) { 
        return this.chartName;
    }
    
    /** SETTER
     * Chart name
     */
    @JsonSetter("chartName")
    public void setChartName (String value) { 
        this.chartName = value;
    }
 
    /** GETTER
     * Chart Date and Time in YYYY-MM-DDTHH:MM:SS format.
     */
    @JsonGetter("chartDate")
    public String getChartDate ( ) { 
        return this.chartDate;
    }
    
    /** SETTER
     * Chart Date and Time in YYYY-MM-DDTHH:MM:SS format.
     */
    @JsonSetter("chartDate")
    public void setChartDate (String value) { 
        this.chartDate = value;
    }
 
    /** GETTER
     * Geographical Longitude.
     */
    @JsonGetter("lng")
    public String getLng ( ) { 
        return this.lng;
    }
    
    /** SETTER
     * Geographical Longitude.
     */
    @JsonSetter("lng")
    public void setLng (String value) { 
        this.lng = value;
    }
 
    /** GETTER
     * Geographical latitude.
     */
    @JsonGetter("lat")
    public String getLat ( ) { 
        return this.lat;
    }
    
    /** SETTER
     * Geographical latitude.
     */
    @JsonSetter("lat")
    public void setLat (String value) { 
        this.lat = value;
    }
 
    /** GETTER
     * Elevation of the geographical location.
     */
    @JsonGetter("elev")
    public int getElev ( ) { 
        return this.elev;
    }
    
    /** SETTER
     * Elevation of the geographical location.
     */
    @JsonSetter("elev")
    public void setElev (int value) { 
        this.elev = value;
    }
 
    /** GETTER
     * Time Zone. You can obtain time zone details by calling the Locations APIs.
     */
    @JsonGetter("tz")
    public String getTz ( ) { 
        return this.tz;
    }
    
    /** SETTER
     * Time Zone. You can obtain time zone details by calling the Locations APIs.
     */
    @JsonSetter("tz")
    public void setTz (String value) { 
        this.tz = value;
    }
 
    /** GETTER
     * 100: Tropical Zodiac: 1: Fagan-Bradley Ayanamsa, 2: Lahiri Ayanamsa; 3: Raman Ayanamsa.
     */
    @JsonGetter("zodiacID")
    public int getZodiacID ( ) { 
        return this.zodiacID;
    }
    
    /** SETTER
     * 100: Tropical Zodiac: 1: Fagan-Bradley Ayanamsa, 2: Lahiri Ayanamsa; 3: Raman Ayanamsa.
     */
    @JsonSetter("zodiacID")
    public void setZodiacID (int value) { 
        this.zodiacID = value;
    }
 
    /** GETTER
     * 1: Placidus; 2: Koch, 3: Porphyrius; 4: Regiomontanus, 20: Whole System.
     */
    @JsonGetter("houseSystemID")
    public int getHouseSystemID ( ) { 
        return this.houseSystemID;
    }
    
    /** SETTER
     * 1: Placidus; 2: Koch, 3: Porphyrius; 4: Regiomontanus, 20: Whole System.
     */
    @JsonSetter("houseSystemID")
    public void setHouseSystemID (int value) { 
        this.houseSystemID = value;
    }
 
    /** GETTER
     * G: Geocentric; T: Topocentric; H: Heliocentric.
     */
    @JsonGetter("coordSys")
    public String getCoordSys ( ) { 
        return this.coordSys;
    }
    
    /** SETTER
     * G: Geocentric; T: Topocentric; H: Heliocentric.
     */
    @JsonSetter("coordSys")
    public void setCoordSys (String value) { 
        this.coordSys = value;
    }
 
    /** GETTER
     * Version of the chart. This may be used by mobile apps that allow editing of the existing charts.
     */
    @JsonGetter("version")
    public int getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * Version of the chart. This may be used by mobile apps that allow editing of the existing charts.
     */
    @JsonSetter("version")
    public void setVersion (int value) { 
        this.version = value;
    }
 
    /** GETTER
     * Path to the generated horoscope image on https://astroapp.com servers.
     */
    @JsonGetter("imgPath")
    public String getImgPath ( ) { 
        return this.imgPath;
    }
    
    /** SETTER
     * Path to the generated horoscope image on https://astroapp.com servers.
     */
    @JsonSetter("imgPath")
    public void setImgPath (String value) { 
        this.imgPath = value;
    }
 
    /** GETTER
     * Julian Date. 0 means the Julian Date is not provided.
     */
    @JsonGetter("jd")
    public Double getJd ( ) { 
        return this.jd;
    }
    
    /** SETTER
     * Julian Date. 0 means the Julian Date is not provided.
     */
    @JsonSetter("jd")
    public void setJd (Double value) { 
        this.jd = value;
    }
 
}
