/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DignitiesResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3823660002461781725L;
    private Chart chart;
    private DignitiesResults output;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chart")
    public Chart getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chart")
    public void setChart (Chart value) { 
        this.chart = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("output")
    public DignitiesResults getOutput ( ) { 
        return this.output;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("output")
    public void setOutput (DignitiesResults value) { 
        this.output = value;
    }
 
}
