/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class DignitiesRequestBuilder {
    //the instance to build
    private DignitiesRequest dignitiesRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DignitiesRequestBuilder() {
        dignitiesRequest = new DignitiesRequest();
    }

    public DignitiesRequestBuilder chart(Chart chart) {
        dignitiesRequest.setChart(chart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DignitiesRequest build() {
        return dignitiesRequest;
    }
}