/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DignitiesResults 
        implements java.io.Serializable {
    private static final long serialVersionUID = 950977844664738722L;
    private List<DignitiesValue> p0;
    private List<DignitiesValue> p1;
    private List<DignitiesValue> p2;
    private List<DignitiesValue> p3;
    private List<DignitiesValue> p4;
    private List<DignitiesValue> p5;
    private List<DignitiesValue> p6;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p0")
    public List<DignitiesValue> getP0 ( ) { 
        return this.p0;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p0")
    public void setP0 (List<DignitiesValue> value) { 
        this.p0 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p1")
    public List<DignitiesValue> getP1 ( ) { 
        return this.p1;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p1")
    public void setP1 (List<DignitiesValue> value) { 
        this.p1 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p2")
    public List<DignitiesValue> getP2 ( ) { 
        return this.p2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p2")
    public void setP2 (List<DignitiesValue> value) { 
        this.p2 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p3")
    public List<DignitiesValue> getP3 ( ) { 
        return this.p3;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p3")
    public void setP3 (List<DignitiesValue> value) { 
        this.p3 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p4")
    public List<DignitiesValue> getP4 ( ) { 
        return this.p4;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p4")
    public void setP4 (List<DignitiesValue> value) { 
        this.p4 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p5")
    public List<DignitiesValue> getP5 ( ) { 
        return this.p5;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p5")
    public void setP5 (List<DignitiesValue> value) { 
        this.p5 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("p6")
    public List<DignitiesValue> getP6 ( ) { 
        return this.p6;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("p6")
    public void setP6 (List<DignitiesValue> value) { 
        this.p6 = value;
    }
 
}
