/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class DignitiesValueBuilder {
    //the instance to build
    private DignitiesValue dignitiesValue;

    /**
     * Default constructor to initialize the instance
     */
    public DignitiesValueBuilder() {
        dignitiesValue = new DignitiesValue();
    }

    public DignitiesValueBuilder rulerId(int rulerId) {
        dignitiesValue.setRulerId(rulerId);
        return this;
    }

    public DignitiesValueBuilder score(int score) {
        dignitiesValue.setScore(score);
        return this;
    }

    public DignitiesValueBuilder typeId(int typeId) {
        dignitiesValue.setTypeId(typeId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DignitiesValue build() {
        return dignitiesValue;
    }
}