/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DignitiesForDatesRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -46999865244300553L;
    private ChartData chart;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chart")
    public ChartData getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chart")
    public void setChart (ChartData value) { 
        this.chart = value;
    }
 
}
