/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class DignitiesForDatesRequestBuilder {
    //the instance to build
    private DignitiesForDatesRequest dignitiesForDatesRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DignitiesForDatesRequestBuilder() {
        dignitiesForDatesRequest = new DignitiesForDatesRequest();
    }

    public DignitiesForDatesRequestBuilder chart(ChartData chart) {
        dignitiesForDatesRequest.setChart(chart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DignitiesForDatesRequest build() {
        return dignitiesForDatesRequest;
    }
}