/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class EventResult 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5521408974480237753L;
    private int aspectAngle;
    private int eventType = 1;
    private String exactDate1;
    private double exactJD;
    private int exactJD2;
    private double exactLng;
    private double exactLng2;
    private int objectId1;
    private int objectId2;
    private String exactDate2;
    /** GETTER
     * Angle of the aspect. For example, 0 is conjunction, 60.0 is sextile, 90 is square and so on.
     */
    @JsonGetter("aspectAngle")
    public int getAspectAngle ( ) { 
        return this.aspectAngle;
    }
    
    /** SETTER
     * Angle of the aspect. For example, 0 is conjunction, 60.0 is sextile, 90 is square and so on.
     */
    @JsonSetter("aspectAngle")
    public void setAspectAngle (int value) { 
        this.aspectAngle = value;
    }
 
    /** GETTER
     * 1: Transit to Planet; 3: Transit to House Cusp.
     */
    @JsonGetter("eventType")
    public int getEventType ( ) { 
        return this.eventType;
    }
    
    /** SETTER
     * 1: Transit to Planet; 3: Transit to House Cusp.
     */
    @JsonSetter("eventType")
    public void setEventType (int value) { 
        this.eventType = value;
    }
 
    /** GETTER
     * The exact date of the event.
     */
    @JsonGetter("exactDate1")
    public String getExactDate1 ( ) { 
        return this.exactDate1;
    }
    
    /** SETTER
     * The exact date of the event.
     */
    @JsonSetter("exactDate1")
    public void setExactDate1 (String value) { 
        this.exactDate1 = value;
    }
 
    /** GETTER
     * Julian Date of the event
     */
    @JsonGetter("exactJD")
    public double getExactJD ( ) { 
        return this.exactJD;
    }
    
    /** SETTER
     * Julian Date of the event
     */
    @JsonSetter("exactJD")
    public void setExactJD (double value) { 
        this.exactJD = value;
    }
 
    /** GETTER
     * The exact date of the 2nd event in series. This can only occur in case of a retrograde planet making the same aspect again.
     */
    @JsonGetter("exactJD2")
    public int getExactJD2 ( ) { 
        return this.exactJD2;
    }
    
    /** SETTER
     * The exact date of the 2nd event in series. This can only occur in case of a retrograde planet making the same aspect again.
     */
    @JsonSetter("exactJD2")
    public void setExactJD2 (int value) { 
        this.exactJD2 = value;
    }
 
    /** GETTER
     * The exact longitude of the aspect (ecliptic coordinates).
     */
    @JsonGetter("exactLng")
    public double getExactLng ( ) { 
        return this.exactLng;
    }
    
    /** SETTER
     * The exact longitude of the aspect (ecliptic coordinates).
     */
    @JsonSetter("exactLng")
    public void setExactLng (double value) { 
        this.exactLng = value;
    }
 
    /** GETTER
     * The exact longitude of the second event aspect (ecliptic coordinates).
     */
    @JsonGetter("exactLng2")
    public double getExactLng2 ( ) { 
        return this.exactLng2;
    }
    
    /** SETTER
     * The exact longitude of the second event aspect (ecliptic coordinates).
     */
    @JsonSetter("exactLng2")
    public void setExactLng2 (double value) { 
        this.exactLng2 = value;
    }
 
    /** GETTER
     * Id of the first object making an aspect or participating in the astrological event.
     */
    @JsonGetter("objectId1")
    public int getObjectId1 ( ) { 
        return this.objectId1;
    }
    
    /** SETTER
     * Id of the first object making an aspect or participating in the astrological event.
     */
    @JsonSetter("objectId1")
    public void setObjectId1 (int value) { 
        this.objectId1 = value;
    }
 
    /** GETTER
     * Id of the second object forming an aspect or participating in the astrological event.
     */
    @JsonGetter("objectId2")
    public int getObjectId2 ( ) { 
        return this.objectId2;
    }
    
    /** SETTER
     * Id of the second object forming an aspect or participating in the astrological event.
     */
    @JsonSetter("objectId2")
    public void setObjectId2 (int value) { 
        this.objectId2 = value;
    }
 
    /** GETTER
     * The exact date of the second event in the events series.
     */
    @JsonGetter("exactDate2")
    public String getExactDate2 ( ) { 
        return this.exactDate2;
    }
    
    /** SETTER
     * The exact date of the second event in the events series.
     */
    @JsonSetter("exactDate2")
    public void setExactDate2 (String value) { 
        this.exactDate2 = value;
    }
 
}
