/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ObjectBuilder {
    //the instance to build
    private Object object;

    /**
     * Default constructor to initialize the instance
     */
    public ObjectBuilder() {
        object = new Object();
    }

    /**
     * Object ID.
     */
    public ObjectBuilder id(int id) {
        object.setId(id);
        return this;
    }

    /**
     * Latitude in Ecliptic coordinates
     */
    public ObjectBuilder lat(int lat) {
        object.setLat(lat);
        return this;
    }

    /**
     * Longitude in Ecliptic coordinates
     */
    public ObjectBuilder lng(double lng) {
        object.setLng(lng);
        return this;
    }

    /**
     * Speed (in Ecliptic coordinates). Negative speed indicates the object is retrograde, 0 speed means the object is stationary.
     */
    public ObjectBuilder speed(double speed) {
        object.setSpeed(speed);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Object build() {
        return object;
    }
}