/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Object 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5423045349588646592L;
    private int id;
    private int lat;
    private double lng;
    private double speed;
    /** GETTER
     * Object ID.
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Object ID.
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
    /** GETTER
     * Latitude in Ecliptic coordinates
     */
    @JsonGetter("lat")
    public int getLat ( ) { 
        return this.lat;
    }
    
    /** SETTER
     * Latitude in Ecliptic coordinates
     */
    @JsonSetter("lat")
    public void setLat (int value) { 
        this.lat = value;
    }
 
    /** GETTER
     * Longitude in Ecliptic coordinates
     */
    @JsonGetter("lng")
    public double getLng ( ) { 
        return this.lng;
    }
    
    /** SETTER
     * Longitude in Ecliptic coordinates
     */
    @JsonSetter("lng")
    public void setLng (double value) { 
        this.lng = value;
    }
 
    /** GETTER
     * Speed (in Ecliptic coordinates). Negative speed indicates the object is retrograde, 0 speed means the object is stationary.
     */
    @JsonGetter("speed")
    public double getSpeed ( ) { 
        return this.speed;
    }
    
    /** SETTER
     * Speed (in Ecliptic coordinates). Negative speed indicates the object is retrograde, 0 speed means the object is stationary.
     */
    @JsonSetter("speed")
    public void setSpeed (double value) { 
        this.speed = value;
    }
 
}
