/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Params 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1162877655239515099L;
    private List<Integer> objects;
    private List<Integer> aspects;
    /** GETTER
     * Array of object / planet IDs to be included.
     */
    @JsonGetter("objects")
    public List<Integer> getObjects ( ) { 
        return this.objects;
    }
    
    /** SETTER
     * Array of object / planet IDs to be included.
     */
    @JsonSetter("objects")
    public void setObjects (List<Integer> value) { 
        this.objects = value;
    }
 
    /** GETTER
     * Array of aspects (aspect angles) to be included.
     */
    @JsonGetter("aspects")
    public List<Integer> getAspects ( ) { 
        return this.aspects;
    }
    
    /** SETTER
     * Array of aspects (aspect angles) to be included.
     */
    @JsonSetter("aspects")
    public void setAspects (List<Integer> value) { 
        this.aspects = value;
    }
 
}
