/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ParamsBuilder {
    //the instance to build
    private Params params;

    /**
     * Default constructor to initialize the instance
     */
    public ParamsBuilder() {
        params = new Params();
    }

    /**
     * Array of object / planet IDs to be included.
     */
    public ParamsBuilder objects(List<Integer> objects) {
        params.setObjects(objects);
        return this;
    }

    /**
     * Array of aspects (aspect angles) to be included.
     */
    public ParamsBuilder aspects(List<Integer> aspects) {
        params.setAspects(aspects);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Params build() {
        return params;
    }
}