/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ProgressionsResponseBuilder {
    //the instance to build
    private ProgressionsResponse progressionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ProgressionsResponseBuilder() {
        progressionsResponse = new ProgressionsResponse();
    }

    public ProgressionsResponseBuilder chart(Chart chart) {
        progressionsResponse.setChart(chart);
        return this;
    }

    public ProgressionsResponseBuilder params(ProgressionParameters params) {
        progressionsResponse.setParams(params);
        return this;
    }

    public ProgressionsResponseBuilder results(List<EventResult> results) {
        progressionsResponse.setResults(results);
        return this;
    }

    public ProgressionsResponseBuilder targetChart(TargetChart targetChart) {
        progressionsResponse.setTargetChart(targetChart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProgressionsResponse build() {
        return progressionsResponse;
    }
}