/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ProgressionParameters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3051603801841303230L;
    private List<Integer> objects;
    private List<Integer> aspects;
    private List<Integer> eventTypes;
    private boolean isHouseIngress = false;
    private Boolean isMansionIngress = false;
    private Boolean isMidpoints = false;
    private Boolean isSignIngress = false;
    private Boolean isStations = false;
    private Boolean isStationsLat = false;
    private boolean isToNatal;
    private Boolean isToProgressed = false;
    private int progressionRate = 0;
    /** GETTER
     * List of objects to be included in calculations.
     */
    @JsonGetter("objects")
    public List<Integer> getObjects ( ) { 
        return this.objects;
    }
    
    /** SETTER
     * List of objects to be included in calculations.
     */
    @JsonSetter("objects")
    public void setObjects (List<Integer> value) { 
        this.objects = value;
    }
 
    /** GETTER
     * List of aspects to include in calculations. This is an array of aspect angles.
     */
    @JsonGetter("aspects")
    public List<Integer> getAspects ( ) { 
        return this.aspects;
    }
    
    /** SETTER
     * List of aspects to include in calculations. This is an array of aspect angles.
     */
    @JsonSetter("aspects")
    public void setAspects (List<Integer> value) { 
        this.aspects = value;
    }
 
    /** GETTER
     * Types of events.
     */
    @JsonGetter("eventTypes")
    public List<Integer> getEventTypes ( ) { 
        return this.eventTypes;
    }
    
    /** SETTER
     * Types of events.
     */
    @JsonSetter("eventTypes")
    public void setEventTypes (List<Integer> value) { 
        this.eventTypes = value;
    }
 
    /** GETTER
     * Flag to include house ingresses
     */
    @JsonGetter("isHouseIngress")
    public boolean getIsHouseIngress ( ) { 
        return this.isHouseIngress;
    }
    
    /** SETTER
     * Flag to include house ingresses
     */
    @JsonSetter("isHouseIngress")
    public void setIsHouseIngress (boolean value) { 
        this.isHouseIngress = value;
    }
 
    /** GETTER
     * Flag to include Lunar Mansion ingresses
     */
    @JsonGetter("isMansionIngress")
    public Boolean getIsMansionIngress ( ) { 
        return this.isMansionIngress;
    }
    
    /** SETTER
     * Flag to include Lunar Mansion ingresses
     */
    @JsonSetter("isMansionIngress")
    public void setIsMansionIngress (Boolean value) { 
        this.isMansionIngress = value;
    }
 
    /** GETTER
     * Flag to include midpoints
     */
    @JsonGetter("isMidpoints")
    public Boolean getIsMidpoints ( ) { 
        return this.isMidpoints;
    }
    
    /** SETTER
     * Flag to include midpoints
     */
    @JsonSetter("isMidpoints")
    public void setIsMidpoints (Boolean value) { 
        this.isMidpoints = value;
    }
 
    /** GETTER
     * Flag to include ingresses in signs
     */
    @JsonGetter("isSignIngress")
    public Boolean getIsSignIngress ( ) { 
        return this.isSignIngress;
    }
    
    /** SETTER
     * Flag to include ingresses in signs
     */
    @JsonSetter("isSignIngress")
    public void setIsSignIngress (Boolean value) { 
        this.isSignIngress = value;
    }
 
    /** GETTER
     * Flag to include planetary stations in longitude events
     */
    @JsonGetter("isStations")
    public Boolean getIsStations ( ) { 
        return this.isStations;
    }
    
    /** SETTER
     * Flag to include planetary stations in longitude events
     */
    @JsonSetter("isStations")
    public void setIsStations (Boolean value) { 
        this.isStations = value;
    }
 
    /** GETTER
     * Flag to include planetary stations in latitude events
     */
    @JsonGetter("isStationsLat")
    public Boolean getIsStationsLat ( ) { 
        return this.isStationsLat;
    }
    
    /** SETTER
     * Flag to include planetary stations in latitude events
     */
    @JsonSetter("isStationsLat")
    public void setIsStationsLat (Boolean value) { 
        this.isStationsLat = value;
    }
 
    /** GETTER
     * Include aspects to natal.
     */
    @JsonGetter("isToNatal")
    public boolean getIsToNatal ( ) { 
        return this.isToNatal;
    }
    
    /** SETTER
     * Include aspects to natal.
     */
    @JsonSetter("isToNatal")
    public void setIsToNatal (boolean value) { 
        this.isToNatal = value;
    }
 
    /** GETTER
     * Include Progressions to Progressions events.
     */
    @JsonGetter("isToProgressed")
    public Boolean getIsToProgressed ( ) { 
        return this.isToProgressed;
    }
    
    /** SETTER
     * Include Progressions to Progressions events.
     */
    @JsonSetter("isToProgressed")
    public void setIsToProgressed (Boolean value) { 
        this.isToProgressed = value;
    }
 
    /** GETTER
     * Progression rate. 0 is a secondary progression
     */
    @JsonGetter("progressionRate")
    public int getProgressionRate ( ) { 
        return this.progressionRate;
    }
    
    /** SETTER
     * Progression rate. 0 is a secondary progression
     */
    @JsonSetter("progressionRate")
    public void setProgressionRate (int value) { 
        this.progressionRate = value;
    }
 
}
