/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ProgressionsRequestBuilder {
    //the instance to build
    private ProgressionsRequest progressionsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ProgressionsRequestBuilder() {
        progressionsRequest = new ProgressionsRequest();
    }

    public ProgressionsRequestBuilder params(ProgressionParameters params) {
        progressionsRequest.setParams(params);
        return this;
    }

    public ProgressionsRequestBuilder targetChart(TargetChart targetChart) {
        progressionsRequest.setTargetChart(targetChart);
        return this;
    }

    public ProgressionsRequestBuilder chart(Chart chart) {
        progressionsRequest.setChart(chart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProgressionsRequest build() {
        return progressionsRequest;
    }
}