/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ReturnsParameters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5330921225123900833L;
    private List<Integer> objects;
    private int bodyId;
    private int harmonicValue;
    private boolean isBackwards;
    private boolean isPast;
    private boolean isPrecess;
    private int retPositionId;
    private int retTypeId;
    private int returnDegree;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("objects")
    public List<Integer> getObjects ( ) { 
        return this.objects;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("objects")
    public void setObjects (List<Integer> value) { 
        this.objects = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bodyId")
    public int getBodyId ( ) { 
        return this.bodyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bodyId")
    public void setBodyId (int value) { 
        this.bodyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("harmonicValue")
    public int getHarmonicValue ( ) { 
        return this.harmonicValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("harmonicValue")
    public void setHarmonicValue (int value) { 
        this.harmonicValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isBackwards")
    public boolean getIsBackwards ( ) { 
        return this.isBackwards;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isBackwards")
    public void setIsBackwards (boolean value) { 
        this.isBackwards = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isPast")
    public boolean getIsPast ( ) { 
        return this.isPast;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isPast")
    public void setIsPast (boolean value) { 
        this.isPast = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isPrecess")
    public boolean getIsPrecess ( ) { 
        return this.isPrecess;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isPrecess")
    public void setIsPrecess (boolean value) { 
        this.isPrecess = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("retPositionId")
    public int getRetPositionId ( ) { 
        return this.retPositionId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("retPositionId")
    public void setRetPositionId (int value) { 
        this.retPositionId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("retTypeId")
    public int getRetTypeId ( ) { 
        return this.retTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("retTypeId")
    public void setRetTypeId (int value) { 
        this.retTypeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("returnDegree")
    public int getReturnDegree ( ) { 
        return this.returnDegree;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("returnDegree")
    public void setReturnDegree (int value) { 
        this.returnDegree = value;
    }
 
}
