/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ReturnsRequestBuilder {
    //the instance to build
    private ReturnsRequest returnsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ReturnsRequestBuilder() {
        returnsRequest = new ReturnsRequest();
    }

    public ReturnsRequestBuilder params(ReturnsParameters params) {
        returnsRequest.setParams(params);
        return this;
    }

    public ReturnsRequestBuilder targetChart(TargetChart targetChart) {
        returnsRequest.setTargetChart(targetChart);
        return this;
    }

    public ReturnsRequestBuilder chart(Chart chart) {
        returnsRequest.setChart(chart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReturnsRequest build() {
        return returnsRequest;
    }
}