/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ReturnsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7607387131402885247L;
    private Chart chart;
    private Chart output;
    private ReturnsParameters params;
    private TargetChart targetChart;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chart")
    public Chart getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chart")
    public void setChart (Chart value) { 
        this.chart = value;
    }
 
    /** GETTER
     * Chart calculated for the moment of the return. The specialPoints array is optional.
     */
    @JsonGetter("output")
    public Chart getOutput ( ) { 
        return this.output;
    }
    
    /** SETTER
     * Chart calculated for the moment of the return. The specialPoints array is optional.
     */
    @JsonSetter("output")
    public void setOutput (Chart value) { 
        this.output = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("params")
    public ReturnsParameters getParams ( ) { 
        return this.params;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("params")
    public void setParams (ReturnsParameters value) { 
        this.params = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("targetChart")
    public TargetChart getTargetChart ( ) { 
        return this.targetChart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("targetChart")
    public void setTargetChart (TargetChart value) { 
        this.targetChart = value;
    }
 
}
