/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ReturnsResponseBuilder {
    //the instance to build
    private ReturnsResponse returnsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ReturnsResponseBuilder() {
        returnsResponse = new ReturnsResponse();
    }

    public ReturnsResponseBuilder chart(Chart chart) {
        returnsResponse.setChart(chart);
        return this;
    }

    /**
     * Chart calculated for the moment of the return. The specialPoints array is optional.
     */
    public ReturnsResponseBuilder output(Chart output) {
        returnsResponse.setOutput(output);
        return this;
    }

    public ReturnsResponseBuilder params(ReturnsParameters params) {
        returnsResponse.setParams(params);
        return this;
    }

    public ReturnsResponseBuilder targetChart(TargetChart targetChart) {
        returnsResponse.setTargetChart(targetChart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReturnsResponse build() {
        return returnsResponse;
    }
}