/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class ReturnsParametersBuilder {
    //the instance to build
    private ReturnsParameters returnsParameters;

    /**
     * Default constructor to initialize the instance
     */
    public ReturnsParametersBuilder() {
        returnsParameters = new ReturnsParameters();
    }

    public ReturnsParametersBuilder objects(List<Integer> objects) {
        returnsParameters.setObjects(objects);
        return this;
    }

    public ReturnsParametersBuilder bodyId(int bodyId) {
        returnsParameters.setBodyId(bodyId);
        return this;
    }

    public ReturnsParametersBuilder harmonicValue(int harmonicValue) {
        returnsParameters.setHarmonicValue(harmonicValue);
        return this;
    }

    public ReturnsParametersBuilder isBackwards(boolean isBackwards) {
        returnsParameters.setIsBackwards(isBackwards);
        return this;
    }

    public ReturnsParametersBuilder isPast(boolean isPast) {
        returnsParameters.setIsPast(isPast);
        return this;
    }

    public ReturnsParametersBuilder isPrecess(boolean isPrecess) {
        returnsParameters.setIsPrecess(isPrecess);
        return this;
    }

    public ReturnsParametersBuilder retPositionId(int retPositionId) {
        returnsParameters.setRetPositionId(retPositionId);
        return this;
    }

    public ReturnsParametersBuilder retTypeId(int retTypeId) {
        returnsParameters.setRetTypeId(retTypeId);
        return this;
    }

    public ReturnsParametersBuilder returnDegree(int returnDegree) {
        returnsParameters.setReturnDegree(returnDegree);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReturnsParameters build() {
        return returnsParameters;
    }
}