/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class StatsBySignRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5597214505617001239L;
    private Chart chart;
    private Params params;
    /** GETTER
     * Chart Data.
     */
    @JsonGetter("chart")
    public Chart getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * Chart Data.
     */
    @JsonSetter("chart")
    public void setChart (Chart value) { 
        this.chart = value;
    }
 
    /** GETTER
     * Calculation parameters
     */
    @JsonGetter("params")
    public Params getParams ( ) { 
        return this.params;
    }
    
    /** SETTER
     * Calculation parameters
     */
    @JsonSetter("params")
    public void setParams (Params value) { 
        this.params = value;
    }
 
}
