/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class StatsBySignRequestBuilder {
    //the instance to build
    private StatsBySignRequest statsBySignRequest;

    /**
     * Default constructor to initialize the instance
     */
    public StatsBySignRequestBuilder() {
        statsBySignRequest = new StatsBySignRequest();
    }

    /**
     * Chart Data.
     */
    public StatsBySignRequestBuilder chart(Chart chart) {
        statsBySignRequest.setChart(chart);
        return this;
    }

    /**
     * Calculation parameters
     */
    public StatsBySignRequestBuilder params(Params params) {
        statsBySignRequest.setParams(params);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StatsBySignRequest build() {
        return statsBySignRequest;
    }
}