/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class StatsBySignResponseBuilder {
    //the instance to build
    private StatsBySignResponse statsBySignResponse;

    /**
     * Default constructor to initialize the instance
     */
    public StatsBySignResponseBuilder() {
        statsBySignResponse = new StatsBySignResponse();
    }

    public StatsBySignResponseBuilder chart(Chart chart) {
        statsBySignResponse.setChart(chart);
        return this;
    }

    public StatsBySignResponseBuilder output(List<Integer> output) {
        statsBySignResponse.setOutput(output);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StatsBySignResponse build() {
        return statsBySignResponse;
    }
}