/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class TargetChartBuilder {
    //the instance to build
    private TargetChart targetChart;

    /**
     * Default constructor to initialize the instance
     */
    public TargetChartBuilder() {
        targetChart = new TargetChart();
    }

    public TargetChartBuilder chartDate(String chartDate) {
        targetChart.setChartDate(chartDate);
        return this;
    }

    public TargetChartBuilder elev(int elev) {
        targetChart.setElev(elev);
        return this;
    }

    public TargetChartBuilder lat(String lat) {
        targetChart.setLat(lat);
        return this;
    }

    public TargetChartBuilder lng(String lng) {
        targetChart.setLng(lng);
        return this;
    }

    public TargetChartBuilder chartName(String chartName) {
        targetChart.setChartName(chartName);
        return this;
    }

    public TargetChartBuilder coordSys(String coordSys) {
        targetChart.setCoordSys(coordSys);
        return this;
    }

    public TargetChartBuilder houseSystemID(String houseSystemID) {
        targetChart.setHouseSystemID(houseSystemID);
        return this;
    }

    public TargetChartBuilder jd(double jd) {
        targetChart.setJd(jd);
        return this;
    }

    public TargetChartBuilder tz(String tz) {
        targetChart.setTz(tz);
        return this;
    }

    public TargetChartBuilder zodiacID(int zodiacID) {
        targetChart.setZodiacID(zodiacID);
        return this;
    }

    public TargetChartBuilder version(int version) {
        targetChart.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TargetChart build() {
        return targetChart;
    }
}