/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TargetChart 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7025880435255063324L;
    private String chartDate;
    private int elev;
    private String lat;
    private String lng;
    private String chartName;
    private String coordSys;
    private String houseSystemID;
    private double jd;
    private String tz;
    private int zodiacID;
    private int version;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chartDate")
    public String getChartDate ( ) { 
        return this.chartDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chartDate")
    public void setChartDate (String value) { 
        this.chartDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("elev")
    public int getElev ( ) { 
        return this.elev;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("elev")
    public void setElev (int value) { 
        this.elev = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lat")
    public String getLat ( ) { 
        return this.lat;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lat")
    public void setLat (String value) { 
        this.lat = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lng")
    public String getLng ( ) { 
        return this.lng;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lng")
    public void setLng (String value) { 
        this.lng = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chartName")
    public String getChartName ( ) { 
        return this.chartName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chartName")
    public void setChartName (String value) { 
        this.chartName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coordSys")
    public String getCoordSys ( ) { 
        return this.coordSys;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coordSys")
    public void setCoordSys (String value) { 
        this.coordSys = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("houseSystemID")
    public String getHouseSystemID ( ) { 
        return this.houseSystemID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("houseSystemID")
    public void setHouseSystemID (String value) { 
        this.houseSystemID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("jd")
    public double getJd ( ) { 
        return this.jd;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("jd")
    public void setJd (double value) { 
        this.jd = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tz")
    public String getTz ( ) { 
        return this.tz;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tz")
    public void setTz (String value) { 
        this.tz = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("zodiacID")
    public int getZodiacID ( ) { 
        return this.zodiacID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("zodiacID")
    public void setZodiacID (int value) { 
        this.zodiacID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("version")
    public int getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("version")
    public void setVersion (int value) { 
        this.version = value;
    }
 
}
