/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TransitsToTransitsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6277177145693685291L;
    private int aspectAngle;
    private int eventType;
    private String exactDate1;
    private String exactDate2;
    private double exactJD;
    private double exactJD2;
    private int exactLng;
    private int exactLng2;
    private int objectId1;
    private int objectId2;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("aspectAngle")
    public int getAspectAngle ( ) { 
        return this.aspectAngle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("aspectAngle")
    public void setAspectAngle (int value) { 
        this.aspectAngle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("eventType")
    public int getEventType ( ) { 
        return this.eventType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("eventType")
    public void setEventType (int value) { 
        this.eventType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exactDate1")
    public String getExactDate1 ( ) { 
        return this.exactDate1;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exactDate1")
    public void setExactDate1 (String value) { 
        this.exactDate1 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exactDate2")
    public String getExactDate2 ( ) { 
        return this.exactDate2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exactDate2")
    public void setExactDate2 (String value) { 
        this.exactDate2 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exactJD")
    public double getExactJD ( ) { 
        return this.exactJD;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exactJD")
    public void setExactJD (double value) { 
        this.exactJD = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exactJD2")
    public double getExactJD2 ( ) { 
        return this.exactJD2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exactJD2")
    public void setExactJD2 (double value) { 
        this.exactJD2 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exactLng")
    public int getExactLng ( ) { 
        return this.exactLng;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exactLng")
    public void setExactLng (int value) { 
        this.exactLng = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exactLng2")
    public int getExactLng2 ( ) { 
        return this.exactLng2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exactLng2")
    public void setExactLng2 (int value) { 
        this.exactLng2 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("objectId1")
    public int getObjectId1 ( ) { 
        return this.objectId1;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("objectId1")
    public void setObjectId1 (int value) { 
        this.objectId1 = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("objectId2")
    public int getObjectId2 ( ) { 
        return this.objectId2;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("objectId2")
    public void setObjectId2 (int value) { 
        this.objectId2 = value;
    }
 
}
