/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TransitsToTransitsRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6186173355950327L;
    private TransitsParameters params;
    /** GETTER
     * Transit parameters.
     */
    @JsonGetter("params")
    public TransitsParameters getParams ( ) { 
        return this.params;
    }
    
    /** SETTER
     * Transit parameters.
     */
    @JsonSetter("params")
    public void setParams (TransitsParameters value) { 
        this.params = value;
    }
 
}
