/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TransitsToNatalResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5010367942790807340L;
    private Chart chart;
    private ProgressionParameters params;
    private List<EventResult> results;
    private TargetChart targetChart;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chart")
    public Chart getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chart")
    public void setChart (Chart value) { 
        this.chart = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("params")
    public ProgressionParameters getParams ( ) { 
        return this.params;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("params")
    public void setParams (ProgressionParameters value) { 
        this.params = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("results")
    public List<EventResult> getResults ( ) { 
        return this.results;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("results")
    public void setResults (List<EventResult> value) { 
        this.results = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("targetChart")
    public TargetChart getTargetChart ( ) { 
        return this.targetChart;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("targetChart")
    public void setTargetChart (TargetChart value) { 
        this.targetChart = value;
    }
 
}
