/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class TransitsToNatalResponseBuilder {
    //the instance to build
    private TransitsToNatalResponse transitsToNatalResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TransitsToNatalResponseBuilder() {
        transitsToNatalResponse = new TransitsToNatalResponse();
    }

    public TransitsToNatalResponseBuilder chart(Chart chart) {
        transitsToNatalResponse.setChart(chart);
        return this;
    }

    public TransitsToNatalResponseBuilder params(ProgressionParameters params) {
        transitsToNatalResponse.setParams(params);
        return this;
    }

    public TransitsToNatalResponseBuilder results(List<EventResult> results) {
        transitsToNatalResponse.setResults(results);
        return this;
    }

    public TransitsToNatalResponseBuilder targetChart(TargetChart targetChart) {
        transitsToNatalResponse.setTargetChart(targetChart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TransitsToNatalResponse build() {
        return transitsToNatalResponse;
    }
}