/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;

public class TransitsToNatalRequestBuilder {
    //the instance to build
    private TransitsToNatalRequest transitsToNatalRequest;

    /**
     * Default constructor to initialize the instance
     */
    public TransitsToNatalRequestBuilder() {
        transitsToNatalRequest = new TransitsToNatalRequest();
    }

    /**
     * Transit parameters.
     */
    public TransitsToNatalRequestBuilder params(TransitsParameters params) {
        transitsToNatalRequest.setParams(params);
        return this;
    }

    /**
     * Chart data
     */
    public TransitsToNatalRequestBuilder chart(Chart chart) {
        transitsToNatalRequest.setChart(chart);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TransitsToNatalRequest build() {
        return transitsToNatalRequest;
    }
}