/*
 * AstroAppRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.astroapp.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TransitsToNatalRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4999624279399350083L;
    private TransitsParameters params;
    private Chart chart;
    /** GETTER
     * Transit parameters.
     */
    @JsonGetter("params")
    public TransitsParameters getParams ( ) { 
        return this.params;
    }
    
    /** SETTER
     * Transit parameters.
     */
    @JsonSetter("params")
    public void setParams (TransitsParameters value) { 
        this.params = value;
    }
 
    /** GETTER
     * Chart data
     */
    @JsonGetter("chart")
    public Chart getChart ( ) { 
        return this.chart;
    }
    
    /** SETTER
     * Chart data
     */
    @JsonSetter("chart")
    public void setChart (Chart value) { 
        this.chart = value;
    }
 
}
